### ISSUE TITLE
Excel / PowerPoint support

### ISSUE THREAD

**Issue by frisch-raphael** [alonrbar/easy-template-x#117]
I'd be interested in creating a fork / making a PR with support for PowerPoint and Excel. I already made a PowerPoint and Excel template engine for [this tool](https://github.com/SerpicoProject/Serpico) a few years ago, but with a vastly different approach. At that time, the strategy was to turn the OpenXML into an XSLT and compile the document through an XSLT transform. Skimming through easy-template-x, I can see that the "compilation" is done by hand.

Have you already thought of adding support for PowerPoint and Excel? If so, do you have any thoughts on how to do that, while keeping the philosophy of the already existing docx templating code? The similarities between the office formats make me think it should not be impossible, but I'm sure I'm missing tons of details.

**Comment by alonrbar** [comment]
Haven't thought about adding PowerPoint and Excel support. Since as you said, the formats are similar, I'd assume some of the code can be reused, but some will have to change. I haven't look into what it will take exactly and of the top of my head it seems like a pretty significant work. My intuition is that it's not something I'm going to support here in the foreseeable future - I have no personal need for it and the amount of work seems non-trivial - so perhaps a fork is more suitable at the moment. Having said that, if you want to take a look at it and bounce some ideas here in I'd be happy to discuss further.

**Comment by alonrbar** [comment]
Closing for now but feel free to reopen and continue the discussion here.
