### ISSUE TITLE
Feature Request: Streams

### ISSUE THREAD

**Issue by andreashuetter** [alonrbar/easy-template-x#121]
Hi, I would like to kindly ask if it is currently planned or possible to offer streams in addition to Blob/Buffer in a future release? From my point of view, it would be a significant gain to be able to pipe data to easy-template-x in a memory-efficient manner and subsequently pass it on to pdfmake, for example, also using a pipe.

**Comment by alonrbar** [comment]
I don't see how I can make the package accept a stream as input. A docx file is essentially a zip file with a bunch of xml files in it. From what I understand zip archives cannot be effectively read as streams due to their internal structure. Adding stream **output** support from the other hand seems relatively easy. But there are two gotchas. First, as the JSZip [documentation](https://stuk.github.io/jszip/documentation/api_jszip/generate_async.html) indicate, files created this way might not be openable by all readers (so not sure if Word or pdfmake will be able to read them, but we can try and see). Second, and the more significant concern with regard to your expectations. This will not make a very big difference in terms of memory footprint. Since the template has to be processed in memory the final document will reside in memory anyway so the memory usage saved is just the one of the output blob copy. To give an example, say we have a template of size y and a resulting document of size x, currently the memory use will be y+2x (one x for the internal representation and one x for the output blob or buffer). Implementing output streams will result in an x+y total memory use, so even though it's less than the current situation it will still be problematic for for large inputs.

Eventually I think the question is, what is the size of input and output you realistically expect and will the resulting reduction actually be significant.

**Comment by andreashuetter** [comment]
I see. Anyway, thanks for looking into it and thank you for the detailed explanation!
