### ISSUE TITLE
Multiple enhancements

### ISSUE THREAD

**Issue by thegnuu** [alonrbar/easy-template-x#14]
@alonrbar I worked quite a while at your project today and changed a few things, here is what I've done:

- Webpack: switched from babel to ts-loader to automatically generate types
- Wepack: switched from UglifyJsPlugin to TerserPlugin because of issues with the new webpack version
- Jest: because of the webpack change i switched to ts-jest to omit the babel configs
- Imports: optimized all imports to relative paths because I ran into some weird issues while generating types
- Imports: switched to one index.ts to provide one entry point for the public api
- Style: added a prettier config and editorconfig
- Plugins: changed a few types to more generic ones like the `PluginContent` to prevent type errors while creating new plugins
- Deps: updated all dependencies

You can find my changes here [https://github.com/bbit-cloud/easy-template-x](https://github.com/bbit-cloud/easy-template-x).

I don't know if you are happy with those changes because I touched nearly every file, if you think this all makes sense I am happy to provide a pull request :)

**Comment by alonrbar** [comment]
Hi,
First of all kudos for the hard work! 
I really understand the desire for change and I myself often feel the same way when entering a new code base. However...

- Regarding babel vs ts-loader - this is a deliberate decision as I'll explain below: 
  - Babel is much more configurable and is the defacto standard in the JS world, and at the end of the day it's usually more productive to stick to the more wide spread standards out there. If you're into it I recommend a nice reading about it [here](https://iamturns.com/typescript-babel/).
  - You've experienced the pain of leaving it yourself when you had to change jest to ts-jest. 
  - You've also experienced it when you had to change the import paths...
  - Even after the migration to ts-jest is done the troubles don't stop as you now cannot use useful tools such as [vscode-jest-runner](https://marketplace.visualstudio.com/items?itemName=firsttris.vscode-jest-runner). 
  - Another issue in the same matter is the plugability of ts-nameof which is a lot easier with babel.
  - I was actually using ts-loader in the past and made the transition in v0.5.0 ([changelog entry](https://github.com/alonrbar/easy-template-x/blob/master/CHANGELOG.md#050---2019-05-07)).
- Switching to TerserPlugin is actually a good idea and I was procrastinating for a while now :) I will check if I can easily incorporate this change in the future.
- To automatically generate type files you can simple use tsc, no need for ts-loader here... I chose to manually do that for the time being because I was not happy with the output of either solutions.
- About styling:
  - This is a matter of personal taste but I don't like prettier. It's not pretty in my eyes 😜
  - Adding editor config is not a bad idea and I may add it, even though some of the configurations there are already covered by eslint.
- Using PluginContent to make it easier to add new plugins is probably the way to go. I tried to make it nicer for intellisense purpose but this is a valid point you're making.
- And finally, updating dependencies is always a good idea :)

I appreciate the good will but I believe a pool request with solely "environmental" changes should generally be avoided. I will try to incorporate as much of the changes you've described in the next release. Even so, if you feel OK with contributing few _small-scoped_ and well defined PR (TerserPlugin, PluginContent, updating dependencies, editorconfig with 4 spaces indent...) it can be helpful and you are more than welcome to do so.

In any case, thanks again!

**Comment by thegnuu** [comment]
Hi

Thank you for looking at my changes and for your response :)

- I think you are totally right about using babel after having a look at your resources! I will have a deeper look at all of this tomorrow :) But I think the automatic generation of typings (I am totally okay with tsc) is a must have - because the typings of the current release ([https://github.com/alonrbar/easy-template-x/blob/master/dist/plugins.d.ts#L18](https://github.com/alonrbar/easy-template-x/blob/master/dist/plugins.d.ts#L18)) are not matching with the code base ([https://github.com/alonrbar/easy-template-x/blob/master/src/plugins/templatePlugin.ts#L13](https://github.com/alonrbar/easy-template-x/blob/master/src/plugins/templatePlugin.ts#L13))
- Styling is a personal taste, of course ;) I personally don't care much about how the code looks as long as it looks the same. It would just make it easier for other people to collaborators if there are some widely used configurations available. Without configuration files my default vs-code setup makes some silly things sometimes...

I will provide you a few pull requests tomorrow:
- A small package.json script to create typings and copy it to dist automatically
- Editorconfig (with 4 idents of course :))
- TerserPlugin
- More generic typings for Plugins
- Dependencies

Thank you for reviewing my changes and for your helpful feedback!

**Comment by alonrbar** [comment]
Thank you for the PRs! They are all closed now so I'm closing this issue as well.

**Comment by thegnuu** [comment]
Great! Thank you for your work! :)
