### ISSUE TITLE
Edge support

### ISSUE THREAD

**Issue by ricsil** [alonrbar/easy-template-x#21]
Hi,

Did you test this against Edge? Can't seem to get it to work, nor does the live demo work on Edge. Firefox seems to run OK, not sure about Chrome.

Getting 

````
0: Invalid calling object easy-template-x.js (1859,1)
````

Presumably in the following code block

````
  async getDocument() {
    if (!this._document) {
      const xml = await this.zip.getFile(this.documentPath).getContentText();
      this._document = this.xmlParser.parse(xml);
    }

    return this._document;
  }
````

**Comment by alonrbar** [comment]
Hi,

Tested it just now on Edge. It seems like CodeSandbox does not support Edge in the first place since I get "Activating extension 'vscode.typescript-language-features' failed: Expected identifier, string or number." error in it's UI. Also see [https://stackoverflow.com/questions/49369343/codesandbox-with-reactjs-nog-working-in-internet-explorer-edge](https://stackoverflow.com/questions/49369343/codesandbox-with-reactjs-nog-working-in-internet-explorer-edge).

I was however able to make the demo work on Edge, after downloading it as zip and running locally.
To achieve this do the following:

1. Open the live demo page on a supported browser (I work with Chrome and I see you've reported it works with Firefox).
2. Click on the "Export to ZIP" button on CodeSandbox's Explorer side bar.
3. Extract to local directory.
4. Run `yarn` or `npm install` to install dependencies.
5. To make it work locally, in `src/env.ts` file change lines 11 and 35 from `const request = await fetch("/res/template.docx");` to `const request = await fetch(require("/res/template.docx"));` (it's a [Parcel](https://parceljs.org/) thing).
6. Run `yarn start` or `npm run start`.
7. Open `localhost:1234` on Edge.
8. Enjoy :)
