### ISSUE TITLE
Converting to PDF

### ISSUE THREAD

**Issue by Frekansapp** [alonrbar/easy-template-x#29]
First of all thanks for this amazing library. Great work.
Is there a chance to add convert to pdf feature? Preferably without 3rd party libraries (LibreOffice etc.)

 [I found this library](https://www.npmjs.com/package/word2pdf-promises?activeTab=readme) but it's too slow with buffer

**Comment by alonrbar** [comment]
Thanks, glad you like it :)

Since you asked I made a short research about the possible ways to achieve this.  
As it turns out converting to docx to pdf is rather complex. How I see it there are 5 main approaches for this task:

1. Generating pdfs from scratch. This would mean to read the docx document token by token and trying to re-create a matching pdf document using one of the many pdf creation libraries out there ([pdfkit](https://github.com/foliojs/pdfkit), [jsPDF](https://github.com/MrRio/jsPDF), [pdfmake](https://github.com/bpampuch/pdfmake)).
2. [Converting to html](https://www.npmjs.com/package/mammoth) and then using browser capabilities. Either [client side](https://itnext.io/javascript-convert-html-css-to-pdf-print-supported-very-sharp-and-not-blurry-c5ffe441eb5e) or server side (using [phantomjs](https://github.com/marcbachmann/node-html-pdf) or [puppeteer](https://blog.risingstack.com/pdf-from-html-node-js-puppeteer/)).
3. Using some native code along with nodejs (on [windows](https://www.npmjs.com/package/node-msoffice-pdf) or [linux](https://www.npmjs.com/package/office-converter) machines).
4. Using an external api ([free](https://www.npmjs.com/package/word2pdf) or [paid](https://medium.com/@cloudmersive/how-to-convert-word-docx-to-pdf-in-node-js-b18e59121950), paid usually have some kind of free tier).
5. Using one of the paid libraries out there ([pdftron](https://www.pdftron.com/documentation/samples/js/OfficeToPDFTest) for instance).

As you can see this by no means a simple or small task and I believe it is out of the scope for this library.

I hope at least that this gives you an idea about the approach most fitting to your use case. 
Good luck!

_Full list of links in this answer:_
- https://github.com/foliojs/pdfkit
- https://github.com/MrRio/jsPDF
- https://github.com/bpampuch/pdfmake
- https://www.npmjs.com/package/mammoth
- https://itnext.io/javascript-convert-html-css-to-pdf-print-supported-very-sharp-and-not-blurry-c5ffe441eb5e
- https://github.com/marcbachmann/node-html-pdf
- https://blog.risingstack.com/pdf-from-html-node-js-puppeteer/
- https://www.npmjs.com/package/node-msoffice-pdf
- https://www.npmjs.com/package/office-converter
- https://www.npmjs.com/package/word2pdf
- https://medium.com/@cloudmersive/how-to-convert-word-docx-to-pdf-in-node-js-b18e59121950
- https://www.pdftron.com/documentation/samples/js/OfficeToPDFTest
