### ISSUE TITLE
Raw xml table cannot be inserted to document via rawXml plugin

### ISSUE THREAD

**Issue by ggalas** [alonrbar/easy-template-x#33]
Hello,

it is any way to insert tables like this: http://officeopenxml.com/WPtable.php to document using rawXml plugin? When i create that table and use rawXml plugin, document after generating is corrupted.

Best regards

**Comment by alonrbar** [comment]
Hi,

That's because tables are "block-level" element (see that first and last paragraphs [here](http://officeopenxml.com/WPcontentOverview.php)), i.e. they can not reside inside paragraphs, while the tag that being replaces is always inside a paragraph since it's a standard text content.

As a side note, the easiest way to understand what's the issue in such cases is to create a valid Word document in the normal way, via Word, extract the document with zip and examine the internal files, usually the `document.xml` file.

The immediate solution to your problem I believe will be to add a flag to the `rawXmlContent` interface, something like `replaceParagraph: boolean`, and implement that behavior in the `rawXmlPlugin`. 

Another good solution would be to create a brand new `tablePlugin` for such use cases.

I'm currently working full time on other projects so I won't have the time to do that myself. You are more than welcome to PR the `rawXmlPlugin` or to create a new `tablePlugin` in a new repo and I will gladly reference it in the readme file.

**Comment by fulgore83** [comment]
Hello, 

I'm sorry but I had to change my account

Thank you for the comprehensive explanation, it helped me a lot. Currently, I did the interface extension as you suggested and everything works great. I will create tests and come back with PR.
