### ISSUE TITLE
array of attachments

### ISSUE THREAD

**Issue by mattia-lau** [alonrbar/easy-template-x#38]
for example:
i have array of images like
```typescript
attachments: [{
          _type: 'image',
          source: readFileSync('hero.png').buffer,
          format: 'images/png',
          width: 200,
          height: 200,
}, {...}, {...}],
```

how should i write the template file?

**Comment by alonrbar** [comment]
Hi @mattia-lau I'm assuming you already got it right by now but for completion, this is how it would work:

**Template**
```
{#attachments}
{pic}
{/attachments}
```

**Data**
```
{
  attachments: [
    {
      pic: {
          _type: 'image',
          source: readFileSync('hero.png').buffer,
          format: 'images/png',
          width: 200,
          height: 200,
       }
    },
    {
      pic: {
          _type: 'image',
          source: readFileSync('hero.png').buffer,
          format: 'images/png',
          width: 200,
          height: 200,
       }
    }
  ]
}
```

Notice that the loop tag iterates an array of _objects_ and looks for the right property(ies) to render on each cycle. That's why you need to declare a "pic" (or any other name you want) property on each object and only inside it specify the image props.
