### ISSUE TITLE
Picture is empty in word file

### ISSUE THREAD

**Issue by fpedeboscq** [alonrbar/easy-template-x#46]
I added an image to a list but only show blank box in word.

{ "Brand": "Carlsberg", 
      "Price": 1 ,
      "image": {
        _type: "image",
        source: fs.readFileSync("./res/image-plugin-out.png"),
        format: "image/png",
        width: 371,
        height: 387
      }
    }

Any help would be grateful.
François

**Comment by alonrbar** [comment]
Hi @fpedeboscq, can you share the template you are using? Notice that template are case sensitive, so that's one thing that can go wrong.
Another thing worth trying is using the tests in [this file](https://github.com/alonrbar/easy-template-x/blob/master/test/fixtures/image.tests.ts) as a working starting point and trying to go forward from there.
Let me know how it goes.

**Comment by fpedeboscq** [comment]
Finally it was an issue in the template word. I had an http link in the template and after removing it pictures appeared. Thanks for your response anyway.
François
