### ISSUE TITLE
Nested loop in a table

### ISSUE THREAD

**Issue by HenriqueSerafim13** [alonrbar/easy-template-x#50]
First of all.. Thank you so much for this library!

I´ve encounter a possible bug when we write something like {#table}{Property1}{#images}{image}{/images}{Property2}{/Table}. All the information is visible but each image is separated with a row with the same information from property1 and property2.

Already tried to separate the tags with new line but with no success.. 

Some prints below.. Any help is appreciated, thanks!

<img width="708" alt="Screenshot 2021-05-20 at 19 54 02" src="https://user-images.githubusercontent.com/84539121/119033583-4a2ae680-b9a5-11eb-9d20-a6d3daeba660.png">
<img width="706" alt="Screenshot 2021-05-20 at 19 54 29" src="https://user-images.githubusercontent.com/84539121/119033586-4ac37d00-b9a5-11eb-9ce3-1e90d0b29c04.png">

**Comment by HenriqueSerafim13** [comment]
PS: Everything is fine with 1 image..

**Comment by alonrbar** [comment]
Hi, happy you enjoy it :)

As for your question, nested loops don't play nicely inside tables. That's because any loop tag inside a table will repeat the entire row, no matter it's location within the row. This behavior is not well documented but you can find it explained [here in the changelog](https://github.com/alonrbar/easy-template-x/blob/master/CHANGELOG.md#050---2019-05-07).
The reason it was designed this way was to simplify the usage and implementation of the table loop. Supporting nested loops inside a table would raise some non-trivial issues.

Unfortunately I cannot provide a real solution for nested loops at the moment. Maybe a workaround would do here?

If you know in advance how many images there will be maybe you can write the template a bit differently.

Another workaround I can think of is writing a custom plugin, say "paragraphLoop", and have it call a copy of the loop plugin with only the [paragraph strategy](https://github.com/alonrbar/easy-template-x/blob/60f1c019f1389df1ff547d1e62e27d6fa27b8179/src/plugins/loop/loopPlugin.ts#L14). The JSON content it will accept would look like this:
```
{
  _type: "paragraphLoop",
  items: [ ... ]
}
```

**Comment by HenriqueSerafim13** [comment]
i was thinking in one alternative.. i´m going to try it and i'll answer in a few moments ;) hope it works..

**Comment by HenriqueSerafim13** [comment]
So.. i found (a not pretty) workaround.. im predicting that each row cant have more than 10 images and i just check my image array how many images there are.. below the prints of the "solution"
![Screenshot 2021-05-21 at 09 24 13](https://user-images.githubusercontent.com/84539121/119107040-ca3d6480-ba16-11eb-8443-3fc65507e329.png)
![Screenshot 2021-05-21 at 09 24 45](https://user-images.githubusercontent.com/84539121/119107044-cc072800-ba16-11eb-9f87-cfd9576049d2.png)
<img width="743" alt="Screenshot 2021-05-21 at 09 25 17" src="https://user-images.githubusercontent.com/84539121/119107055-cdd0eb80-ba16-11eb-889a-eeb5fbd739af.png">

**Comment by rRakarare** [comment]
Hey guys, i got a pretty simple workaround for the given problem. Just put the loop inside the table in a second table like this:
![image](https://user-images.githubusercontent.com/53125940/123096916-e2e2d500-d42f-11eb-84e5-d33a8e093de4.png)

Works fine !

**Comment by eitanfr** [comment]
> Hey guys, i got a pretty simple workaround for the given problem. Just put the loop inside the table in a second table like this: ![image](https://user-images.githubusercontent.com/53125940/123096916-e2e2d500-d42f-11eb-84e5-d33a8e093de4.png)
> 
> Works fine !

Awesome workaround, creating an inner table with no borders does the trick.

**Comment by alonrbar** [comment]
Fixed in v4.0.0
