### ISSUE TITLE
I wrote an extension that adds minimal HTML styling.

### ISSUE THREAD

**Issue by cvaize** [alonrbar/easy-template-x#72]
At this stage I needed to process the tags: `<br>`, `<b></b>`, `<i></i>`, `<u></u>`.
I am waiting for your feedback and suggestions.
https://github.com/cvaize/easy-template-x-extension-html

I plan to add lists, links, styling via style, headers from 1-6 levels later.

**Comment by alonrbar** [comment]
Hi, I'm on a vacation with no access to my laptop until the end of the month. Will take a look when I get back home. Thank you!

**Comment by alonrbar** [comment]
Hi again,

First of all, looks really nice!

Some points I've noticed:

1. In the code example in the README file you can import `createDefaultPlugins` and then just append to it. Alternatively you can create a `new TemplateHandlerOptions()` and then append to it's [plugins](https://github.com/alonrbar/easy-template-x/blob/7281ee81db9b2cdcb547ddf4402027b38fe8a024/src/templateHandlerOptions.ts#L8) field.
2. nit: In the same code example you created two `handler` variables...
3. `index.js` is well organized, but personally I prefer splitting things to files to make it easier to read each of them. It makes a great difference in my eyes. I would go for `htmlPlugin.js`, `htmlObject.js` and probably a `utils.js`, or at least something like this.
4. Instead of iterating the run nodes of the paragraph [here](https://github.com/cvaize/easy-template-x-extension-html/blob/a79aec7afc2d4f33cb8e5f2194fb899b1968598d/src/index.js#L263) you can use `XmlNode.remove(runNode)`. like I'm doing [here](https://github.com/alonrbar/easy-template-x/blob/7281ee81db9b2cdcb547ddf4402027b38fe8a024/src/plugins/image/imagePlugin.ts#L44) for instance.
5. `findChildByName` [already exists](https://github.com/alonrbar/easy-template-x/blob/7281ee81db9b2cdcb547ddf4402027b38fe8a024/src/xml/xmlNode.ts#L438) so you can use it instead of [this one](https://github.com/cvaize/easy-template-x-extension-html/blob/a79aec7afc2d4f33cb8e5f2194fb899b1968598d/src/index.js#L345).
6. Again, personal style but I prefer reverting the if logic to get reduced indentation so instead of 
```javascript
copyAttributes(fromNode, toNode) {
  if (fromNode.attributes) {
    // do stuff
  }
}
```
I'd go for 
```javascript
copyAttributes(fromNode, toNode) {
  if (!fromNode.attributes) {
    return;
  }
  // do stuff
}
```
This is a common idiom. Check [this source](https://dev.to/zachsnoek/clean-up-your-code-by-removing-unneeded-indentation-3g9i) for instance for a more elaborate example for why it's a good practice.
Same goes for the createRun function which can benefit from the practice as well.

If you want, I will be happy to review further and dig deeper into the code of `HtmlObject.splitTextByTags`, `HtmlObject.build` and `HtmlPlugin.createRun` after this first iteration is done.

**Comment by alonrbar** [comment]
Hi, closing this one for now. Feel free to reopen if you ever want to continue the discussion here.
