### ISSUE TITLE
RawXML module document corruption

### ISSUE THREAD

**Issue by whekin** [alonrbar/easy-template-x#81]
Many xml tags have to be in their own w:r. So does the Link module, it doesn't just insert xml, it create a separate w:r node, inherits styles and inserts the link there. So should do RawXML module I think.

It was a issue for me when inserting content controls. I ended up duplicating & modifying the link module to insert content controls correctly

**Comment by alonrbar** [comment]
Did you try setting `replaceParagraph` to false? See the comment in the example data here: https://github.com/alonrbar/easy-template-x#raw-xml-plugin

**Comment by alonrbar** [comment]
If this doesn't work for your case then a new plugin does seem like the right choice. The rawXml plugin is meant for simple insertions, if you need to create runs or otherwise modify the structure of the document then a dedicated plugin is a better alternative. If you think your plugin can be useful to others I always encourage publishing it and I can link to it from the readme.
