### ISSUE TITLE
Node has no parent (two loops in the same table row)

### ISSUE THREAD

**Issue by apostolovskisimon** [alonrbar/easy-template-x#85]
I followed your guide for adding a list of links in the template from here https://github.com/alonrbar/easy-template-x/issues/78

Here is the data: 

 ![image](https://user-images.githubusercontent.com/54365240/227198727-03056a1a-a1b9-4853-9b1b-844835ee543e.png)

Before the opening [ bracket there is links: [... its just not shown in the console.

![image](https://user-images.githubusercontent.com/54365240/227199595-cd8d2245-c459-4461-8e37-4580df5f358e.png)

and the template 

![image](https://user-images.githubusercontent.com/54365240/227198808-4c250ee4-15fa-4e57-aee9-304661c5a28f.png)

With the #links part in the template its throwing node has no parent 

![image](https://user-images.githubusercontent.com/54365240/227199065-0e123aa6-d2ab-42d0-982e-6a79d8cc0edf.png)

Without it it renders just fine.

Here is the word template 
[word_cv_template.docx](https://github.com/alonrbar/easy-template-x/files/11050573/word_cv_template.docx)

**Comment by alonrbar** [comment]
Bug confirmed and needs some investigation. Thank you for reporting this.

**Comment by alonrbar** [comment]
Seems like the issue happens when there are two loops in the same table row:

![two loops](https://user-images.githubusercontent.com/24767479/229311890-2de8f941-f6ef-4382-978a-6b7a0c20f994.PNG)

A temporary workaround may be to put each of these loops in an inner table with just a single cell.

**Comment by melbarra88** [comment]
I have a similar issue, but with conditions within a table : 
for example : 
![template-3 docx  -  Mode de compatibilité - Word](https://user-images.githubusercontent.com/8996002/229347818-52177cb5-4a90-47b1-bc30-f322c3cd8bc7.jpg)

this throws the "Node has no parent" error. 

However, it is worth mensioning that I have no problem with nested loops : 
![template-3 docx  -  Mode de compatibilité - Word_2](https://user-images.githubusercontent.com/8996002/229348032-a2c4f213-a74c-4f9f-9e88-a31fe2f94d75.jpg)

**Comment by opoudjis** [comment]
The latter impacts me as well, and applies to list items as well as tables. Clearly this runs deep in the code — the code is not dealing with calling loops/conditions twice on the same node in the Word structure. But @melbarra88 ’s issue means no multiple choice options in rendering of tables or lists, and that choices have to be made JSON-side rather than template-side. That's a design choice consistent with the original design, but it is locking out a lot of logic from the template. 

Is this related to the long-running nested loop issue from #50 ?

**Comment by alonrbar** [comment]
Fixed in v4.0.0
